services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live:/etc/letsencrypt/live:ro
      - ./index.html::/usr/share/nginx/html/index.html
    ports:
      - "8080:80"

networks:
  passmanager_default:
    external: true