services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/pass.tmanti.dev/fullchain.pem:/etc/nginx/ssl/pass/fullchain.pem
      - /etc/letsencrypt/live/pass.tmanti.dev/privkey.pem:/etc/nginx/ssl/pass/privkey.pem
      - /etc/letsencrypt/live/tmanti.dev/fullchain.pem:/etc/nginx/ssl/root/fullchain.pem
      - /etc/letsencrypt/live/tmanti.dev/privkey.pem:/etc/nginx/ssl/root/privkey.pem
      - ./index.html:/usr/share/nginx/html/index.html
    ports:
      - "80:80"
      - "443:443"
    networks:
      - passmanager_default

networks:
  passmanager_default:
    external: true