services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live:/etc/nginx/certs/
      - ./index.html:/usr/share/nginx/html/index.html
    ports:
      - "80:80"
      - "443:443"
    networks:
      - passmanager_default

networks:
  passmanager_default:
    external: true